trigger:
- master

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu-16.04'
  timeoutInMinutes: 15
  steps:
  - task: Gradle@2
    inputs:
      tasks: test
      gradleOptions: -Xmx3072m
      jdkVersionOption: 1.8
      publishJUnitResults: true
      testResultsFiles: 'library/build/test-results/**/TEST-*.xml'
